# multinomial action selector
action_selector: "multinomial"
epsilon_start: 1.0
epsilon_finish: .05
epsilon_anneal_time: 50000
mask_before_softmax: False

runner: "episode"

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
c_lr: 0.0005

agent_output_type: "pi_logits"
td_lambda: 0.8
learner: "fop_learner"

name: "fop"
buffer_size: 5000

mixing_embed_dim: 32
n_head: 4  
burn_in_period: 100
